[package]
name = "rustracer"
version = "0.1.0"
authors = ["丁科 <dingke@tuya.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
rand = "0.7"
